import InventoryReport from "../components/inventory";

const Test = async () => {
  const res = await fetch(`https://stage-api-rghm.iran.liara.run/reports/products`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization:
        "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI2NzQzZmFhOThiMTcxZTAxMzU1ZDZhMWUiLCJyb2xlIjoidXNlciIsInVzZXJJRCI6IjY2ZjkyODgzMzBmYWZhNTU4MmE1YmFhNCIsImlhdCI6MTczMjUwODMyOSwiZXhwIjoxNzMzNDA4MzI5fQ.wGJ7N2qzCbcOc1SdvJi3lKEQEj6isBb8Q-T4fdeDNUs",
    },
    body: JSON.stringify({
      from: null,
      to: null,
    }),
  });
  const data = await res.json();
  return (
    <div>
      <InventoryReport
        data={{
          currency: "irr",
          range: {
            from: null,
            to: null,
          },
          createdBy: {
            phone: "+989177367655",
            name: "حسین فرخی",
          },
          stats: {
            initialValue: 0,
            latestValue: 101193870000497120000,
            inbounds: {
              count: 29,
              value: "1.323592965464967e+21",
            },
            outbounds: {
              count: 31,
              value: "-1.2236005432402725e+21",
            },
          },
          items: [
            {
              id: "66b07447644b7894186931e2",
              name: "a",
              desc: null,
              unit: "عدد",
              initialQuantity: "0.00",
              initialValue: null,
              latestQuantity: "0.00",
              latestValue: null,
              inbounds: null,
              outbounds: null,
            },
            {
              id: "65f9a1bab5b595558f93cf2b",
              name: "s",
              desc: null,
              unit: "عدد",
              initialQuantity: "0.00",
              initialValue: "0.00",
              latestQuantity: "1.04",
              latestValue: "20883.20",
              inbounds: {
                initialQuantity: null,
                initialPrice: null,
                initialValue: null,
                latestQuantity: "1.04",
                latestPrice: 20080,
                latestValue: "20883.20",
                count: 1,
                amount: "1.04",
                value: "20883.20",
              },
              outbounds: null,
            },
            {
              id: "6729d09f8323949ad2a55729",
              name: "اسب",
              desc: null,
              unit: "راس",
              initialQuantity: "0.00",
              initialValue: null,
              latestQuantity: "0.00",
              latestValue: null,
              inbounds: null,
              outbounds: null,
            },
            {
              id: "65a4ca3ccc9f0830782c3714",
              name: "رانی",
              desc: null,
              unit: "عدد",
              initialQuantity: "0.00",
              initialValue: null,
              latestQuantity: "0.00",
              latestValue: null,
              inbounds: null,
              outbounds: null,
            },
            {
              id: "630331eaeda7598befb7752c",
              name: "سیب",
              desc: "سیب سمیرم",
              unit: "کیلو",
              initialQuantity: "0.00",
              initialValue: "0.00",
              latestQuantity: "31165.00",
              latestValue: "311650000.00",
              inbounds: {
                initialQuantity: null,
                initialPrice: null,
                initialValue: null,
                latestQuantity: "34570.00",
                latestPrice: 10000,
                latestValue: "345700000.00",
                count: 7,
                amount: "34570.00",
                value: "812900000.00",
              },
              outbounds: {
                initialQuantity: null,
                latestQuantity: "-3405.00",
                count: 13,
                amount: "-3405.00",
                value: "-178446000.00",
              },
            },
            {
              id: "65a4ca00cc9f0830782c369e",
              name: "سیب ۴",
              desc: null,
              unit: "کیلوگرم",
              initialQuantity: "0.00",
              initialValue: "0.00",
              latestQuantity: "2.00",
              latestValue: "400000.00",
              inbounds: {
                initialQuantity: null,
                initialPrice: null,
                initialValue: null,
                latestQuantity: "2.00",
                latestPrice: 200000,
                latestValue: "400000.00",
                count: 1,
                amount: "2.00",
                value: "400000.00",
              },
              outbounds: null,
            },
            {
              id: "64569292e633b497ca4a696d",
              name: "سیب دو",
              desc: null,
              unit: "کیلو",
              initialQuantity: "0.00",
              initialValue: "0.00",
              latestQuantity: "51.00",
              latestValue: "102000.00",
              inbounds: {
                initialQuantity: null,
                initialPrice: null,
                initialValue: null,
                latestQuantity: "56.00",
                latestPrice: 2000,
                latestValue: "112000.00",
                count: 2,
                amount: "56.00",
                value: "112000.00",
              },
              outbounds: {
                initialQuantity: null,
                latestQuantity: "-5.00",
                count: 3,
                amount: "-5.00",
                value: "-10000.00",
              },
            },
            {
              id: "65f70d280445f53e0fa3bfb8",
              name: "سیب سرخ ترش یونانی لبنانی سبز",
              desc: null,
              unit: "کیلوگرم",
              initialQuantity: "0.00",
              initialValue: "0.00",
              latestQuantity: "10005.00",
              latestValue: "500250.00",
              inbounds: {
                initialQuantity: null,
                initialPrice: null,
                initialValue: null,
                latestQuantity: "10005.00",
                latestPrice: 50,
                latestValue: "500250.00",
                count: 2,
                amount: "10005.00",
                value: "500250.00",
              },
              outbounds: null,
            },
            {
              id: "65a4c9f8cc9f0830782c3694",
              name: "سیب سه",
              desc: null,
              unit: "کیلوگرم",
              initialQuantity: "0.00",
              initialValue: null,
              latestQuantity: "0.00",
              latestValue: null,
              inbounds: null,
              outbounds: null,
            },
            {
              id: "66b254ab70a28a7bbc0a8fff",
              name: "سیب قرمز",
              desc: "ههه",
              unit: "کیلوگرم",
              initialQuantity: "0.00",
              initialValue: null,
              latestQuantity: "0.00",
              latestValue: null,
              inbounds: null,
              outbounds: null,
            },
            {
              id: "65a4ca25cc9f0830782c36e7",
              name: "شامپو",
              desc: null,
              unit: "عدد",
              initialQuantity: "0.00",
              initialValue: "0.00",
              latestQuantity: "1998.00",
              latestValue: "19980000.00",
              inbounds: {
                initialQuantity: null,
                initialPrice: null,
                initialValue: null,
                latestQuantity: "2000.00",
                latestPrice: 10000,
                latestValue: "20000000.00",
                count: 1,
                amount: "2000.00",
                value: "20000000.00",
              },
              outbounds: {
                initialQuantity: null,
                latestQuantity: "-2.00",
                count: 1,
                amount: "-2.00",
                value: "-40000.00",
              },
            },
            {
              id: "6729d05f8323949ad2a55724",
              name: "شکلات تلخ",
              desc: null,
              unit: "کیلوگرم",
              initialQuantity: "0.00",
              initialValue: "0.00",
              latestQuantity: "3000.00",
              latestValue: "150000000.00",
              inbounds: {
                initialQuantity: null,
                initialPrice: null,
                initialValue: null,
                latestQuantity: "3000.00",
                latestPrice: 50000,
                latestValue: "150000000.00",
                count: 1,
                amount: "3000.00",
                value: "150000000.00",
              },
              outbounds: null,
            },
            {
              id: "66b2555e70a28a7bbc0a900b",
              name: "عالم ",
              desc: null,
              unit: "لللل",
              initialQuantity: "0.00",
              initialValue: "0.00",
              latestQuantity: "1.00",
              latestValue: "2000000.00",
              inbounds: {
                initialQuantity: null,
                initialPrice: null,
                initialValue: null,
                latestQuantity: "1.00",
                latestPrice: 2000000,
                latestValue: "2000000.00",
                count: 1,
                amount: "1.00",
                value: "2000000.00",
              },
              outbounds: null,
            },
            {
              id: "65a4ca49cc9f0830782c372c",
              name: "فاروق",
              desc: null,
              unit: "عدد",
              initialQuantity: "0.00",
              initialValue: "0.00",
              latestQuantity: "2.00",
              latestValue: "4000.00",
              inbounds: {
                initialQuantity: null,
                initialPrice: null,
                initialValue: null,
                latestQuantity: "2.00",
                latestPrice: 2000,
                latestValue: "4000.00",
                count: 1,
                amount: "2.00",
                value: "4000.00",
              },
              outbounds: null,
            },
            {
              id: "65a4ca2fcc9f0830782c36f7",
              name: "فانتوم",
              desc: null,
              unit: "عدد",
              initialQuantity: "0.00",
              initialValue: "0.00",
              latestQuantity: "101193.87",
              latestValue: "101193869999998988061.30",
              inbounds: {
                initialQuantity: null,
                initialPrice: null,
                initialValue: null,
                latestQuantity: "101199.00",
                latestPrice: 999999999999990,
                latestValue: "101198999999998988010.00",
                count: 2,
                amount: "101199.00",
                value: "99999000000001400010.00",
              },
              outbounds: {
                initialQuantity: null,
                latestQuantity: "-5.13",
                count: 2,
                amount: "-5.13",
                value: "-109233.10",
              },
            },
            {
              id: "65a4ca11cc9f0830782c36af",
              name: "کیوی",
              desc: null,
              unit: "کیلوگرم",
              initialQuantity: "0.00",
              initialValue: "0.00",
              latestQuantity: "35.00",
              latestValue: "3500000.00",
              inbounds: {
                initialQuantity: null,
                initialPrice: null,
                initialValue: null,
                latestQuantity: "2041.00",
                latestPrice: 100000,
                latestValue: "204100000.00",
                count: 6,
                amount: "2041.00",
                value: "1708840000.00",
              },
              outbounds: {
                initialQuantity: null,
                latestQuantity: "-2006.00",
                count: 5,
                amount: "-2006.00",
                value: "-40115010.00",
              },
            },
            {
              id: "65a4ca09cc9f0830782c36a8",
              name: "موز",
              desc: null,
              unit: "کیلوگرم",
              initialQuantity: "0.00",
              initialValue: "0.00",
              latestQuantity: "4979.00",
              latestValue: "9958000.00",
              inbounds: {
                initialQuantity: null,
                initialPrice: null,
                initialValue: null,
                latestQuantity: "5000.00",
                latestPrice: 2000,
                latestValue: "10000000.00",
                count: 1,
                amount: "5000.00",
                value: "10000000.00",
              },
              outbounds: {
                initialQuantity: null,
                latestQuantity: "-21.00",
                count: 1,
                amount: "-21.00",
                value: "-10500000.00",
              },
            },
            {
              id: "66b2551d70a28a7bbc0a9004",
              name: "موزر",
              desc: null,
              unit: "کیلو",
              initialQuantity: "0.00",
              initialValue: "0.00",
              latestQuantity: "0.00",
              latestValue: "0.00",
              inbounds: {
                initialQuantity: null,
                initialPrice: null,
                initialValue: null,
                latestQuantity: "1.00",
                latestPrice: 20000,
                latestValue: "20000.00",
                count: 1,
                amount: "1.00",
                value: "20000.00",
              },
              outbounds: {
                initialQuantity: null,
                latestQuantity: "-1.00",
                count: 1,
                amount: "-1.00",
                value: "-20000.00",
              },
            },
            {
              id: "66b3230f7f72df3436d36c27",
              name: "موسیقی متن فیلم های اخیر در سال های اخیر",
              desc: null,
              unit: "ففف",
              initialQuantity: "0.00",
              initialValue: "0.00",
              latestQuantity: "-666.00",
              latestValue: "-6577777777939920.00",
              inbounds: {
                initialQuantity: null,
                initialPrice: null,
                initialValue: null,
                latestQuantity: "123888889.00",
                latestPrice: 9876543210120,
                latestValue: "1223593965462260356680.00",
                count: 1,
                amount: "123888889.00",
                value: "1223593965462260356680.00",
              },
              outbounds: {
                initialQuantity: null,
                latestQuantity: "-123889555.00",
                count: 2,
                amount: "-123889555.00",
                value: "-1223600543240038296600.00",
              },
            },
            {
              id: "65a4ca1bcc9f0830782c36c4",
              name: "نارنگی",
              desc: null,
              unit: "کیلوگرم",
              initialQuantity: "0.00",
              initialValue: "0.00",
              latestQuantity: "-4.57",
              latestValue: "-914000.00",
              inbounds: {
                initialQuantity: null,
                initialPrice: null,
                initialValue: null,
                latestQuantity: "2.56",
                latestPrice: 200000,
                latestValue: "512000.00",
                count: 1,
                amount: "2.56",
                value: "512000.00",
              },
              outbounds: {
                initialQuantity: null,
                latestQuantity: "-7.13",
                count: 3,
                amount: "-7.13",
                value: "-5049233.10",
              },
            },
          ],
        }}
      />
    </div>
  );
};

export default Test;
